"""Change code_generated_time to DateTime

Revision ID: bed5f76c3332
Revises: 
Create Date: 2025-04-13 20:43:44.407259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed5f76c3332'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('temporary_status',
               existing_type=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("('Active')"))
        batch_op.alter_column('code_generated_time',
               existing_type=sa.VARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.alter_column('code_generated_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('temporary_status',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('Active')"))

    # ### end Alembic commands ###
