"""Initial migration

Revision ID: cfe617382c9d
Revises: 
Create Date: 2025-05-04 23:36:47.070714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'cfe617382c9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop the default constraint on 'temporary_status' if it exists
    op.execute("""
        DECLARE @constraint_name NVARCHAR(255)
        SELECT @constraint_name = dc.name
        FROM sys.default_constraints dc
        INNER JOIN sys.columns c ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
        WHERE OBJECT_NAME(dc.parent_object_id) = 'users' AND c.name = 'temporary_status'
        IF @constraint_name IS NOT NULL
            EXEC('ALTER TABLE users DROP CONSTRAINT ' + @constraint_name)
    """)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('expiration_time',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('temporary_status',
               existing_type=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('code_generated_time',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('is_super_user',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.alter_column('is_super_user',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.alter_column('code_generated_time',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
        batch_op.alter_column('temporary_status',
               existing_type=sa.String(length=50),
               type_=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('Active')"))
        batch_op.alter_column('expiration_time',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    op.create_table('UserLogins',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('name', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('status', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('method', sa.NVARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('message', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__UserLogi__3213E83FD832AC6B')
    )
    # ### end Alembic commands ###
