"""Add encrypted_user_id column to users table

Revision ID: e1f9d752b7e8
Revises: 
Create Date: 2025-03-15 03:35:06.927824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'e1f9d752b7e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_user_id', sa.String(length=256), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_encrypted_user_id'), ['encrypted_user_id'], unique=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=12, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_encrypted_user_id'))
        batch_op.drop_column('encrypted_user_id')

    # ### end Alembic commands ###
